[project]
name = "Diploma-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.5.1",
    "fastapi>=0.115.12",
    "pre-commit>=4.2.0",
    "redis>=5.2.1",
    "ruff>=0.11.6",
    "uvicorn>=0.34.2",
]
